{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "23e471c2",
   "metadata": {},
   "outputs": [],
   "source": [
    "import baostock as bs\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import time\n",
    "import requests\n",
    "from bs4 import BeautifulSoup\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.decomposition import PCA\n",
    "from sklearn.linear_model import LogisticRegression\n",
    "import warnings\n",
    "\n",
    "# 屏蔽警告\n",
    "warnings.filterwarnings('ignore')\n",
    "# 解决matplotlib中文乱码\n",
    "plt.rcParams['font.sans-serif'] = ['SimHei']\n",
    "plt.rcParams['axes.unicode_minus'] = False\n",
    "\n",
    "# 20只A股蓝筹代码映射\n",
    "stock_map = {\n",
    "    \"sh.600000\": \"600000\", \"sh.600036\": \"600036\", \"sh.601318\": \"601318\",\n",
    "    \"sh.601398\": \"601398\", \"sh.601988\": \"601988\", \"sh.601288\": \"601288\",\n",
    "    \"sh.601668\": \"601668\", \"sz.000001\": \"000001\", \"sh.600104\": \"600104\",\n",
    "    \"sh.600016\": \"600016\", \"sh.601166\": \"601166\", \"sh.601328\": \"601328\",\n",
    "    \"sh.601818\": \"601818\", \"sh.601088\": \"601088\", \"sh.601601\": \"601601\",\n",
    "    \"sh.601336\": \"601336\", \"sh.600519\": \"600519\", \"sh.600030\": \"600030\",\n",
    "    \"sh.600019\": \"600019\", \"sh.601857\": \"601857\"\n",
    "}\n",
    "\n",
    "# 回测时间区间、基准指数\n",
    "start_date = \"2025-01-01\"\n",
    "end_date = \"2026-05-25\"\n",
    "benchmark_code = \"sh.000300\"\n",
    "\n",
    "fin_data = []\n",
    "# 循环爬取财务数据（网易页面解析失败，异常分支填充模拟数据）\n",
    "for bs_code, code in stock_map.items():\n",
    "    try:\n",
    "        url = f\"http://quotes.money.163.com/trade/{'1' if code.startswith('6') else '0'}{code}.html#01b05\"\n",
    "        res = requests.get(url, timeout=5)\n",
    "        soup = BeautifulSoup(res.text, 'html.parser')\n",
    "        # 原网页解析失效，此处仅占位，无真实数据提取逻辑\n",
    "        fin_data.append({\n",
    "            \"ts_code\": bs_code,\n",
    "            \"roe\": 12.0,\n",
    "            \"bps\": 6.0,\n",
    "            \"收入同比\": 8.0,\n",
    "            \"利润同比\": 10.0,\n",
    "            \"资产负债率\": 60.0\n",
    "        })\n",
    "    except Exception as e:\n",
    "        # 网页访问/解析失败，填充兜底模拟财务指标\n",
    "        fin_data.append({\n",
    "            \"ts_code\": bs_code,\n",
    "            \"roe\": 11.0,\n",
    "            \"bps\": 5.5,\n",
    "            \"收入同比\": 7.0,\n",
    "            \"利润同比\": 9.0,\n",
    "            \"资产负债率\": 62.0\n",
    "        })\n",
    "    time.sleep(0.3)\n",
    "\n",
    "# 财务数据预处理\n",
    "df_fin = pd.DataFrame(fin_data)\n",
    "numeric_cols = [\"roe\", \"bps\", \"收入同比\", \"利润同比\", \"资产负债率\"]\n",
    "for col in numeric_cols:\n",
    "    df_fin[col] = pd.to_numeric(df_fin[col], errors='coerce')\n",
    "    df_fin[col] = df_fin[col].fillna(df_fin[col].mean())\n",
    "\n",
    "# PCA综合打分选股\n",
    "scaler = StandardScaler()\n",
    "X_std = scaler.fit_transform(df_fin[numeric_cols])\n",
    "pca = PCA(n_components=0.95)\n",
    "Y = pca.fit_transform(X_std)\n",
    "df_fin[\"score\"] = np.sum(Y * pca.explained_variance_ratio_, axis=1)\n",
    "# 筛选前12只基本面优质股票\n",
    "top_stocks = df_fin.sort_values(\"score\", ascending=False).head(12)[\"ts_code\"].tolist()\n",
    "\n",
    "# 登录baostock获取行情数据\n",
    "bs.login()\n",
    "k_list = []\n",
    "for code in top_stocks:\n",
    "    rs = bs.query_history_k_data_plus(\n",
    "        code=code,\n",
    "        fields=\"date,open,high,low,close,volume\",\n",
    "        start_date=start_date,\n",
    "        end_date=end_date\n",
    "    )\n",
    "    df = rs.get_data().replace(\"\", np.nan).dropna()\n",
    "    df[\"code\"] = code\n",
    "    k_list.append(df)\n",
    "\n",
    "# 获取沪深300基准行情\n",
    "bench_rs = bs.query_history_k_data_plus(\n",
    "    code=benchmark_code,\n",
    "    fields=\"date,open,close\",\n",
    "    start_date=start_date,\n",
    "    end_date=end_date\n",
    ")\n",
    "df_bench = bench_rs.get_data().replace(\"\", np.nan).dropna()\n",
    "bs.logout()\n",
    "\n",
    "# 拼接全部个股行情并数值转换\n",
    "k_df = pd.concat(k_list)\n",
    "num_cols = [\"open\", \"high\", \"low\", \"close\", \"volume\"]\n",
    "k_df[num_cols] = k_df[num_cols].apply(pd.to_numeric, errors=\"coerce\")\n",
    "df_bench[[\"open\", \"close\"]] = df_bench[[\"open\", \"close\"]].apply(pd.to_numeric, errors=\"coerce\")\n",
    "\n",
    "# 技术指标计算函数\n",
    "def MA(c, n):\n",
    "    return c.rolling(n).mean()\n",
    "\n",
    "def MACD(c):\n",
    "    e12 = c.ewm(span=12).mean()\n",
    "    e26 = c.ewm(span=26).mean()\n",
    "    dif = e12 - e26\n",
    "    dea = dif.ewm(span=9).mean()\n",
    "    return 2 * (dif - dea)\n",
    "\n",
    "def KDJ(h, l, c):\n",
    "    hh = h.rolling(9).max()\n",
    "    ll = l.rolling(9).min()\n",
    "    rsv = (c - ll) / (hh - ll) * 100\n",
    "    k = rsv.ewm(alpha=1/3).mean()\n",
    "    d = k.ewm(alpha=1/3).mean()\n",
    "    j = 3 * k - 2 * d\n",
    "    return k, d, j\n",
    "\n",
    "def RSI(c, n):\n",
    "    diff = c.diff()\n",
    "    up = diff.mask(diff < 0, 0)\n",
    "    dn = -diff.mask(diff > 0, 0)\n",
    "    sum_up = up.rolling(n).sum()\n",
    "    sum_dn = dn.rolling(n).sum()\n",
    "    return sum_up / (sum_up + sum_dn) * 100\n",
    "\n",
    "# 构建机器学习数据集\n",
    "all_data = []\n",
    "for code in top_stocks:\n",
    "    d = k_df[k_df[\"code\"] == code].sort_values(\"date\")\n",
    "    if len(d) < 60:\n",
    "        continue\n",
    "    c = d[\"close\"]\n",
    "    d[\"ma5\"] = MA(c, 5)\n",
    "    d[\"ma10\"] = MA(c, 10)\n",
    "    d[\"ma20\"] = MA(c, 20)\n",
    "    d[\"macd\"] = MACD(c)\n",
    "    d[\"k\"], d[\"d\"], d[\"j\"] = KDJ(d[\"high\"], d[\"low\"], c)\n",
    "    d[\"rsi6\"] = RSI(c, 6)\n",
    "    # 标签：未来3日上涨超1%为1，否则-1\n",
    "    d[\"y\"] = np.where(c.shift(-3) > c * 1.01, 1, -1)\n",
    "    all_data.append(d)\n",
    "\n",
    "model_df = pd.concat(all_data).dropna()\n",
    "feats = [\"ma5\", \"ma10\", \"ma20\", \"macd\", \"k\", \"d\", \"j\", \"rsi6\"]\n",
    "\n",
    "# 划分训练集、测试集\n",
    "split = int(len(model_df) * 0.8)\n",
    "train, test = model_df.iloc[:split], model_df.iloc[split:]\n",
    "Xtrain = scaler.fit_transform(train[feats])\n",
    "ytrain = train[\"y\"]\n",
    "\n",
    "# 逻辑回归模型训练\n",
    "model = LogisticRegression(max_iter=1000)\n",
    "model.fit(Xtrain, ytrain)\n",
    "acc = model.score(Xtrain, ytrain)\n",
    "test = test.reset_index(drop=True)\n",
    "\n",
    "# 计算策略收益率\n",
    "str_returns = []\n",
    "for i in range(len(test) - 3):\n",
    "    buy_price = test[\"open\"].iloc[i+1]\n",
    "    sell_price = test[\"close\"].iloc[i+3]\n",
    "    str_returns.append((sell_price - buy_price) / buy_price)\n",
    "\n",
    "# 计算沪深300基准收益率\n",
    "bench_returns = []\n",
    "for i in range(len(df_bench) - 3):\n",
    "    b_buy = df_bench[\"open\"].iloc[i+1]\n",
    "    b_sell = df_bench[\"close\"].iloc[i+3]\n",
    "    bench_returns.append((b_sell - b_buy) / b_buy)\n",
    "\n",
    "# 收益汇总\n",
    "strategy_return = sum(str_returns)\n",
    "bench_return = sum(bench_returns)\n",
    "excess_return = strategy_return - bench_return\n",
    "\n",
    "# 输出指标\n",
    "print(f\"逻辑回归准确率:{acc:.2%}\")\n",
    "print(f\"策略总收益率:{strategy_return:.2%}\")\n",
    "print(f\"沪深300 基准收益率:{bench_return:.2%}\")\n",
    "print(f\"超额收益:{excess_return:.2%}\")\n",
    "\n",
    "# 净值曲线绘图\n",
    "net1 = np.cumprod(1 + np.array(str_returns))\n",
    "net2 = np.cumprod(1 + np.array(bench_returns[:len(str_returns)]))\n",
    "plt.figure(figsize=(12, 5))\n",
    "plt.plot(net1, label=\"量化策略净值\", linewidth=2)\n",
    "plt.plot(net2, label=\"沪深300 基准净值\", linestyle=\"--\")\n",
    "plt.axhline(1, color=\"gray\", linestyle=\":\")\n",
    "plt.legend()\n",
    "plt.grid(alpha=0.3)\n",
    "plt.show()"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
